// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IAntDesignLikeFilled: typeof import('~icons/ant-design/like-filled')['default']
    IBxBxsCategoryAlt: typeof import('~icons/bx/bxs-category-alt')['default']
    IIconoirChatBubble: typeof import('~icons/iconoir/chat-bubble')['default']
    IIcOutlineAlternateEmail: typeof import('~icons/ic/outline-alternate-email')['default']
    IIcRoundVpnKey: typeof import('~icons/ic/round-vpn-key')['default']
    IIcSharpSettings: typeof import('~icons/ic/sharp-settings')['default']
    IIonChatbubbleEllipses: typeof import('~icons/ion/chatbubble-ellipses')['default']
    IIonHeart: typeof import('~icons/ion/heart')['default']
    ILucideSearch: typeof import('~icons/lucide/search')['default']
    IMaterialSymbolsAdd: typeof import('~icons/material-symbols/add')['default']
    IMaterialSymbolsArrowCircleRight: typeof import('~icons/material-symbols/arrow-circle-right')['default']
    IMaterialSymbolsArrowForwardRounded: typeof import('~icons/material-symbols/arrow-forward-rounded')['default']
    IMaterialSymbolsBookmarkAddRounded: typeof import('~icons/material-symbols/bookmark-add-rounded')['default']
    IMaterialSymbolsClose: typeof import('~icons/material-symbols/close')['default']
    IMaterialSymbolsShare: typeof import('~icons/material-symbols/share')['default']
    IMdiDotsVertical: typeof import('~icons/mdi/dots-vertical')['default']
    IMdiPencilCircle: typeof import('~icons/mdi/pencil-circle')['default']
    IOcticonIssueDraft16: typeof import('~icons/octicon/issue-draft16')['default']
    IRiCompass3Fill: typeof import('~icons/ri/compass3-fill')['default']
    IRiUser4Fill: typeof import('~icons/ri/user4-fill')['default']
    ITablerSearch: typeof import('~icons/tabler/search')['default']
  }
}
