// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IIcOutlineAlternateEmail: typeof import('~icons/ic/outline-alternate-email')['default']
    IIcRoundVpnKey: typeof import('~icons/ic/round-vpn-key')['default']
    IMaterialSymbolsArrowCircleRight: typeof import('~icons/material-symbols/arrow-circle-right')['default']
    IMaterialSymbolsClose: typeof import('~icons/material-symbols/close')['default']
    IRiCompass3Fill: typeof import('~icons/ri/compass3-fill')['default']
    IRiUser4Fill: typeof import('~icons/ri/user4-fill')['default']
  }
}
